---
- hosts: all
  become: true
  
  tasks:
  - name: Stop and remove container
    docker_container:
      name: devops-demo-proj
      state: absent
  - name: Remove image
    docker_image:
      name: devops-demo-proj
      state: absent
      tag: v1
  - name: Building Docker image using war file.
    docker_image: 
      name: devops-demo-proj
      build:
        path: /opt/docker
      tag: v1
      source: build
  - name: Create a container
#    command: docker run -d --name devops-demo-proj -p 8080:8080 devops-demo-proj:v1
    docker_container:
      name: devops-demo-proj
      image: devops-demo-proj:v1
      ports:
      - "8080:8080"
      state: started   
      recreate: yes
