---
- name: integrate-with-ansible-deploy
  hosts: k8s-master 
  user: ubuntu
 
  tasks: 
  - name: Create a deployment
    command: kubectl apply -f devops-demo-deploy.yaml
    
  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/devops-demo-proj-deploy
